{
    'name': 'Freight Forwarding',
    'version': '1.0',
    'summary': 'Custom Module for Freight Forwarding Management (Clavis Group)',
    'description': """
        Modul custom untuk operasional Freight Forwarding.
    """,
    'category': 'Logistics',
    'author': 'IT Dev Clavis',
    'website': '',
    'license': 'LGPL-3',
    'depends': [
        'base', 
        'sale_management',
        'purchase',
        'contacts'
    ],
    'data': [
    # Security
    'security/ir.model.access.csv',
    'security/acct/ir.model.access.csv',
    'security/air/ir.model.access.csv',
    'security/master_data/ir.model.access.csv',
    'security/sea/ir.model.access.csv',
    'security/sea/sales/ir.model.access.csv',
    'security/sea/master_data/ir.model.access.csv',
    # Data
    'data/air/air_booking_sequence.xml',
    'data/air/air_mawb_sequence.xml',
    'data/sea/sea_booking_sequence.xml',
    'data/sea/sea_hbl_sequence.xml',
    # Action
    'views/air/master_data/partner.xml',
    'views/sea/partner.xml',
    'views/transport/partner.xml',
    'views/acct/partner.xml',
    'views/product.xml',
    
    # Sea Quotation (moved from old quotation folder)
    'views/sea/sales/quotation_type.xml',
    'views/sea/sales/quotation.xml',
    'views/sea/sales/cargo_info.xml',
    'views/sea/sales/rate_enquiry_actions.xml',
    'views/sea/booking/booking.xml',
    'views/sea/booking/extra_info_views.xml',
    'views/sea/booking/bl_info_views.xml',
    'views/sea/booking/shipment_info_views.xml',
    'views/sea/booking/vessel_details_views.xml',
    'views/sea/booking/pickup_info_views.xml',
    'views/sea/booking/cargo_info_views.xml',
    'views/sea/booking/purchase_line_views.xml',
    'views/sea/booking/booking_convert_wizard.xml',
    'views/sea/hbl/cargo_info.xml',
    'views/sea/hbl/custom_permit.xml',
    'views/sea/hbl/shipment_info_views.xml',
    'views/sea/hbl/vessel_details_views.xml',
    'views/sea/hbl/purchase_order_views.xml',
    'views/sea/hbl/sales_order_views.xml',
    'views/sea/hbl/tax_refund_doc_views.xml',
    'views/sea/hbl/document_list_views.xml',
    'views/sea/hbl/hbl.xml',
    'report/sea/hbl/hbl_report_template.xml',
    'report/sea/hbl/hbl_report.xml',
    'views/sea/import/purchasing.xml',
    # Acct
    'views/acct/area.xml',
    'views/acct/payment_term.xml',
    'views/acct/vat_code.xml',

    # Air
    'views/air/air_waybill/airline.xml',
    'views/air/air_waybill/airport.xml',
    'views/air/air_waybill/air_booking.xml',
    'views/air/air_waybill/mawb.xml',
    'views/air/air_waybill/custom_permit.xml',
    'views/air/air_waybill/package_details.xml',
    'views/air/air_waybill/document_list.xml',
    'views/air/air_waybill/freight_items_line.xml',
    'views/air/air_waybill/extra_info.xml',
    'views/air/air_waybill/handling_information.xml',
    'views/air/air_waybill/air_waybill_transaction.xml',
    # Master Data
    'views/air/master_data/delivery_type.xml',
    'views/air/master_data/commodity.xml',
    'views/air/master_data/insurance.xml',
    'views/air/master_data/pickup.xml',
    'views/air/master_data/container_type.xml',
    'views/air/master_data/cargo_type.xml',
    'views/air/master_data/contact.xml',
    'views/air/master_data/tag.xml',
    'views/air/master_data/city.xml',
    'views/air/master_data/country.xml',
    'views/air/master_data/incoterms.xml',
    'views/air/air_waybill/airline.xml',
    'views/sea/master_data/port.xml',
    'views/sea/master_data/carrier.xml',
    'views/sea/master_data/shipping_line.xml',
    'views/sea/master_data/vessel.xml',
    'views/sea/master_data/location.xml',
    'views/sea/master_data/incoterm.xml',
    'views/sea/master_data/permit.xml',
    'views/sea/master_data/salesman.xml',
    'views/sea/master_data/product_cost_menu_actions.xml',
    'views/sea/master_data/footer_remark.xml',
    'views/sea/master_data/instruction.xml',

    # Menu
    'views/menu.xml',
    'views/menus/air/master_data/menu.xml',
    'views/menus/partner.xml',
    'views/menus/acct.xml',
    'views/menus/air/air_waybill/menu.xml',
    'views/menus/air/sales/menu.xml',
    'views/menus/air/imports/menu.xml',
    'views/menus/air/export/menu.xml',
    'views/menus/sea/master_data/menu.xml',
    'views/menus/sea/sales/menu.xml',
    'views/menus/sea/imports/booking.xml',
    'views/menus/sea/imports/import_job.xml',
    'views/menus/sea/imports/purchasing.xml',
    'views/menus/sea/imports/invoicing.xml',
    'views/menus/sea/imports/statistical_analysis.xml',
    'views/menus/sea/imports/report.xml',
    'views/menus/sea/export/root.xml',
    'views/menus/sea/export/booking/menu.xml',
    'views/menus/sea/export/job/menu.xml',
    'views/menus/sea/export/purchasing/menu.xml',
    'views/menus/sea/export/invoicing/menu.xml',
    'views/menus/sea/export/statistical_analysis/menu.xml',
    'views/menus/sea/export/report/menu.xml',
    'views/menus/transport.xml',
    'views/menus/others.xml',
],
    'installable': True,
    'application': True,
    'auto_install': False,
}
