from . import air_booking
from . import mawb
from . import extra_info
from . import handling_information
from . import custom_permit
from . import package_details
from . import freight_items_line
from . import document_list
from . import air_waybill_transaction