{
    'name': 'ME Master Data',
    'version': '18.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Master Data Material ME Kontraktor',
    'description': 'Hierarki klasifikasi material: Category → Item Category → Sub Category → Brand',
    'author': 'Clavis Dev',
    'depends': ['product', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/product_category_views.xml',
        'views/mst_brand_views.xml',
        'views/mst_item_category_views.xml',
        'views/mst_sub_category_views.xml',
        'views/product_template_views.xml',
        'views/menu_views.xml',
        'data/demo_data.xml',
    ],
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
