{
    'name': 'Construction QC — ME Quality Control',
    'version': '18.0.1.0.0',
    'category': 'Construction/Project',
    'summary': 'QC Inspection, NCR, Corrective Action & Progress Billing for ME Contractors',
    'author': 'Clavis Development',
    'license': 'LGPL-3',
    'depends': [
        'project',
        'mail',
        'uom',
        'construction_management',
    ],
    'data': [
        'security/qc_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'report/qc_inspection_report.xml',
        'report/qc_report_templates.xml',
        'views/qc_inspection_views.xml',
        'views/qc_ncr_views.xml',
        'views/qc_corrective_action_views.xml',
        'views/qc_checklist_template_views.xml',
        'views/qc_wizard_views.xml',
        'views/qc_dashboard_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'construction_qc/static/src/components/qc_dashboard/qc_dashboard.js',
            'construction_qc/static/src/components/qc_dashboard/qc_dashboard.xml',
            'construction_qc/static/src/components/qc_dashboard/qc_dashboard.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
