{
    'name': 'Construction Management',
    'version': '18.0.1.0.1',
    'category': 'Industries',
    'summary': 'BOQ, Rate Analysis, RA Billing, Job Costing — Construction Suite for Odoo 18',
    'author': 'Custom Development',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'account',
        'analytic',
        'account_budget',
        'sale_management',
        'purchase',
        'stock',
        'project',
        'hr_timesheet',
        'uom',
    ],
    'data': [
        'security/construction_security.xml',
        'security/ir.model.access.csv',
        'data/construction_sequence.xml',
        'data/construction_data.xml',
        'views/construction_job_contract_views.xml',
        'views/view_cop_line.xml',
        'views/construction_boq_views.xml',
        'views/construction_rate_analysis_views.xml',
        'views/construction_ra_billing_views.xml',
        'views/construction_work_order_views.xml',
        'views/construction_material_req_views.xml',
        'views/construction_subcontract_views.xml',
        'views/construction_budget_views.xml',
        'views/construction_job_costing_views.xml',
        'views/construction_scrap_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
